baseURL = 'https://syrno.net/'
languageCode = 'en-us'
title = 'syrno.net'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  blogTitle = "Blog"
  blogDescription = "Random bits of information I find interesting"

[outputs]
  section = ["HTML", "RSS"]

[taxonomies]
  tag = "tags"
